### ISSUE TITLE
Projects page - separate WIP from completed projects AND remove status filter

### ISSUE THREAD

**Issue by lianilychee** [open-austin/website-v2-vercel#15]
![PXL_20221122_204029039~2.jpg](https://user-images.githubusercontent.com/6895034/203417515-a724baf1-f24c-4cc9-8885-d5df79bdf09b.jpg)

**Comment by newswim** [comment]
What did you have in mind for how they should be separated? And would the categories filter still have an effect on what's shown?

**Comment by lianilychee** [comment]
@newswim updated the ticket with a low fi mock

**Comment by newswim** [comment]
Looks great! Thanks Liani -- I'll try to set aside some time this weekend to work on this.
