### ISSUE TITLE
(incomplete ticket) Declutter the nav

### ISSUE THREAD

**Issue by lianilychee** [open-austin/website-v2-vercel#16]
will fill in this ticket based on https://open-austin.slack.com/archives/C03A77BFGRM/p1669010523976019

wip mock - https://miro.com/app/board/o9J_kiLXbtA=/?moveToWidget=3458764539145609364&cot=14

**Comment by attali-david** [comment]
Is there a finalized nav? The Miro seems to contain two or three versions.

**Comment by lianilychee** [comment]
duplicates #50
