### ISSUE TITLE
Projects page - Add indigent stats project

### ISSUE THREAD

**Issue by lianilychee** [open-austin/website-v2-vercel#20]
# Draft card body

Indigent Defense Stats
As an indigent defense advocate, I want to collect data about the public defender process/system so that I can perform evidence-based advocacy for systems change.
Links: ___
Categories: ___

# Notes
Dan Minshew:
- has final say on the title's wording
- can provide links
- can provide categories. I think "legal system" or "justice system" work, but since he's that project's lead, he has final say

**Comment by lianilychee** [comment]
I actually kind of wanna take this issue 🤓

It looks like I would only have to modify the project_data.ts file. @newswim @attali-david , is that accurate?

**Comment by attali-david** [comment]
@lianilychee Yes! You can just copy and paste one of the project objects and alter the values with the project information.

**Comment by lianilychee** [comment]
Thank you! I'll do this once I return to Austin this week. AKA return to my computer so I can create a feature branch

**Comment by newswim** [comment]
closed by https://github.com/open-austin/website-v2-vercel/pull/29
