### ISSUE TITLE
Footer logo overlaps page body

### ISSUE THREAD

**Issue by lianilychee** [open-austin/website-v2-vercel#22]
# Summary

Footer logo overlaps page body, per screenshot. This only occurs on the projects page; I verified by toggling dark mode on all other pages on two browsers.

**Severity:** Low. Not a blocker to going live, since page body text is still legible 

# Environment info

OS: Android 13
Browser: AdBlock Browser, then double checked on Chrome

# Screenshot

![Screenshot_20221123-103121.png](https://user-images.githubusercontent.com/6895034/203622338-f78d2b72-ba97-4f57-ab3d-e19112225ae4.png)

**Comment by lianilychee** [comment]
Now pretty much ALL of the footer is overlapped 

![Screenshot_20221126-103001.png](https://user-images.githubusercontent.com/6895034/204103781-8dc3d3a0-1ef3-42e9-8e85-649405259f4d.png)

**Comment by attali-david** [comment]
I noticed this while working on #15. I'm fairly certain this was a container issue on the portfolio page, and it's no longer an issue. Let me know if the problem persists.

**Comment by lianilychee** [comment]
@attali-david it is still an issue! 

Screenshot from live site

![Screenshot_20221126-172120.png](https://user-images.githubusercontent.com/6895034/204115045-1dfbf4a2-99f8-4cba-b73d-a1cdc415bcc2.png)
