### ISSUE TITLE
Buttons have an underline on hover

### ISSUE THREAD

**Issue by newswim** [open-austin/website-v2-vercel#26]
Not sure what's happening here, I assume it's getting wrapped in a link and not using the `passHref` prop.

Here's the relevant section from the Next docs:
- https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-functional-component

I suspect this is the line that needs to be altered:
https://github.com/open-austin/website-v2-vercel/blob/3655eff72a5c8a304188a8616663491d6de0e201/components/projectHeader.tsx#L17-L19

#### Preview
<img width="494" alt="image" src="https://user-images.githubusercontent.com/6667096/204161627-58e8a44c-d0f9-4b39-98fd-5a136c29da56.png">

**Comment by attali-david** [comment]
The documentation refers to components that are wrapped in Link tags. I asked myself if this applies to a component library and then I thought about wrapping every link in a React.forwardRef(). Instead, I set textDecoration = none on the link component.
