### ISSUE TITLE
Remove `'chakra-react-select'` from project dependencies

### ISSUE THREAD

**Issue by newswim** [open-austin/website-v2-vercel#27]
As of #24 the filters are no longer used, so we can go ahead and drop the project dependency.

**Comment by lianilychee** [comment]
I dunno this ticket context or anything about chakra react, but _about the filtering:_ It's possible that filtering will return in a V2 iteration. Probable, even. However, we will want to consider filtering along with the entire page's UX - how many deployed projects are we showing, what wording are we choosing to describe tech/category/etc, other considerations.

**Comment by newswim** [comment]
That makes sense, it's very easy to add this library (or another library) whenever we need it. For now, it's just increasing the bundle size.
