### ISSUE TITLE
Update this repo's README

### ISSUE THREAD

**Issue by newswim** [open-austin/website-v2-vercel#38]
Right now it just has the boilerplate README from the Next.js.

We should still include instructions for how to develop the site, but we should include more information at the top of the README to talk about who we are and how to find us.

**Comment by tjdev7** [comment]
Do you have a copy of the text for the "who we are" and "how to find us" in any external drive or should I use some of the text that's inside the Open Austin website?

**Comment by tjdev7** [comment]
To learn about Open Austin and how to find us, visit [open-austin.org](https://www.open-austin.org/)

**Comment by tjdev7** [comment]
Issue is being worked on in PR branch #98
