### ISSUE TITLE
Add "Join Slack" page

### ISSUE THREAD

**Issue by newswim** [open-austin/website-v2-vercel#46]
On the old site, we’d used [something like this](https://elements.heroku.com/buttons/outsideris/slack-invite-automation) to create a Slack invite button. Heroku has since closed down their free tier, so we need a different solution. There's already a link in the navbar, but we need a page for users to email their email and be sent an invite to our workspace.

Since our app is hosted on Vercel, we can easily create functions for free. Here’s [an example](https://github.com/open-austin/indigent-stats-frontend/tree/main/pages/api) of how we’re doing that on the Indigent Defense Stats project.

There’s some more info [here](https://github.com/vercel/vercel/discussions/6039) about how to create a Slack Bot. I don’t think this exactly the thing we’re looking for, but does have an example of how to interact with the Slack API (which is what we want).

I managed to find the PR when the SlackIn widget was first added:
https://github.com/open-austin/open-austin.github.io/issues/99

It looks like this might be the endpoint we want to use:
https://api.slack.com/methods/admin.users.invite

### Reqs
- I'm imagining that we'll have a page with one form input field, `Enter Email`, and when you hit enter, it sends that email to our lambda function which will invite that user.
- A little bit of state to handle the HTTP request cycle (loading, error, success).
- Add API token to Vercel backend
- Add `.env` environment for testing locally (optional)

**Comment by kjohnson8781** [comment]
After investigating further, the api method we were looking at is restricted to enterprise workspaces only. 

As a workaround, we were thinking:
Create a Shared Invite Link:

    You can generate a shared invite link manually from your Slack workspace. Here’s how:

    From your desktop, click on your workspace name in the top left.
    Select “Invite people to [Your Workspace]“.
    Click on “Share invite link to join”.
    Copy this link and distribute it.

    On your website, you can include a form that users can submit their email. Once the form is submitted, you could send them an automated email with the shared invite link. One alternative could be to create a function on Vercel that sends them an email with the link. That way we’d also have a record of their emails addresses. We could keep those in a Google Spreadsheet.     

Reqs:
1. Generate an invite link (never expire vs timed?)
2. Create a Vercel Fn that sends the user an email with the link
3. Create page that has a form for user to enter their email that calls the vercel function when the user submits

Reach Goals?
1. Restrict users to guest role
2. Automate switching user from guest to full user based on some criteria that would deter spam accounts

**Comment by kjohnson8781** [comment]
Since we have Google Automated emails already set up, it would be easiest to just set up an automated email that triggers on a specific subject line. I discussed with @lianilychee and @JennyYennyful . 

I am adding the mailto link to our slack invite navigation link with some instructions. @lianilychee is going to set up the mail rules to auto-reply.
