### ISSUE TITLE
Add "Coming Soon" to Join Slack

### ISSUE THREAD

**Issue by attali-david** [open-austin/website-v2-vercel#79]
The Join Slack button is broken. Until we have a working solution, users should not be able to click on the Join Slack button and be redirected to a broken link. Add a "Coming Soon" banner to the right of Join Slack like you see with Onboarding.

<img width="795" alt="Screenshot 2023-06-25 at 1 16 04 PM" src="https://github.com/open-austin/website-v2-vercel/assets/84137250/4403fa7f-e706-471e-b217-c31394884945">

**Comment by lianilychee** [comment]
@teeshaa you can submit a PR without being assigned the ticket!

**Comment by kjohnson8781** [comment]
This will no longer be needed after this merge: https://github.com/open-austin/website-v2-vercel/pull/86
